name: BedWars1058-MapSelector
version: ${project.version}
author: itz_leoo
main: me.leoo.bedwars.mapselector.MapSelector
description: BedWars1058/BedwarsProxy Map Selector Addon
softdepend:
  - BedWarsProxy
  - BedWars1058
  - PlaceholderAPI