name: BedWars1058-MapSelector
version: 1.3.1.1
author: itz_leoo
main: me.leoo.bedwars.mapselector.MapSelector
description: BedWars1058/BedwarsProxy Map Selector Addon
softdepend: [ BedWarsProxy, BedWars1058, PlaceholderAPI ]
permissions:
    bwselector.reload:
        default: op
        description: Permissions required to run the command /bwselector reload